version: '3'
services:
    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: larq
            POSTGRES_DB: larq
            POSTGRES_PASSWORD: larq
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - '5432:5432'
volumes:
    db:
